
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_order
    description: "A starter dbt model"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
         
  - name: cumulative_sales
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null 
          
  - name: dates
  - name: ephim
  - name: incremental_time
  - name: custom_variable_usage
  - name: relationship_test  
    columns:
        - name: id 
          tests:
            - relationships:
                to: ref('my_first_dbt_model')
                field: id
                
  - name: playing_with_tests
    columns:
        - name: c_custkey
          tests:
            - not_null
            - unique
        - name: c_mktsegment
          tests:
            - accepted_values:
                values: ['BUILDING' ,'AUTOMOBILE' ,'MACHINERY' ,'HOUSEHOLD' ,'FURNITURE']
                
  
              